apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors-api
  description: Spring Sensors
  tags:
    - app-accelerator
    - java
    - spring
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
spec:
  type: service
  lifecycle: experimental
  owner: team-spring-sensors-catalog
  providesApis:
    - sensors-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sensors-api
  description: API for sensor data
spec:
  type: openapi
  lifecycle: experimental
  owner: team-spring-sensors-catalog
  definition:
    $text: ./api-docs.json