apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors-service
  description: Spring Sensors Management Service
  tags:
    - spring
    - sensors
    - service
    - java
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors-rabbit'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://spring.io/
      title: Spring makes Java simple, modern, productive, reactive, cloud-ready
spec:
  type: service
  lifecycle: experimental
  owner: team-spring-sensors-catalog
  system: spring-sensors-system
  dependsOn:
    - Component:spring-sensors-catalog-management-rmq